name: Update Menu Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Чтобы ты мог нажать кнопку "Run workflow" для теста

# Добавляем права на запись
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm' # Кэширование ускорит запуск

      - name: Install dependencies
        run: npm install

      - name: Run parser
        run: node parser.js # Убедись, что файл называется так

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add menu.json buffet.json
          # Проверка на наличие изменений, чтобы не падать с ошибкой, если ничего не поменялось
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: automated menu update $(date)" && git push)